--################################################CODIGOS CREACION STG Y DIM_SUCURSAL #####################

CREATE TABLE STG_SUCURSAL(
    CODIGO_SUCURSAL VARCHAR2(10),
    NOMBRE VARCHAR2(40),
    CIUDAD VARCHAR2(20),
    DIRECCION VARCHAR2(100),
    TELEFONO VARCHAR2(15)
);


CREATE TABLE DIM_SUCURSAL(
    SK_NUM_DIM_SUCURSAL NUMBER(3),
    STR_CODIGO_SUCURSAL VARCHAR2(10),
    STR_NOMBRE VARCHAR2(40),
    STR_CIUDAD VARCHAR2(20),
    STR_DIRECCION VARCHAR2(100),
    STR_TELEFONO VARCHAR2(15),
    DT_FECHA_INICIO DATE,
    DT_FECHA_ACTUALIZACION DATE
);


CREATE SEQUENCE SK_NUM_DIM_SUCURSAL
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


--#######################################################CODIGOS CREACION STG Y DIM EMPLEADO################
CREATE TABLE STG_EMPLEADO(
    CODIGO_EMPLEADO VARCHAR2(10),
    NOMBRE VARCHAR2(50),
    APELLIDO1 VARCHAR2(50),
    TELEFONO VARCHAR2(15),
    CORREO VARCHAR2(100),
    PUESTO VARCHAR2(50)
);


CREATE TABLE DIM_EMPLEADO(
    SK_NUM_DIM_EMPLEADO NUMBER(4),
    STR_CODIGO_EMPLEADO VARCHAR2(10),
    STR_NOMBRE VARCHAR2(50),
    STR_APELLIDO1 VARCHAR2(50),
    STR_TELEFONO VARCHAR2(15),
    STR_CORREO VARCHAR2(100),
    STR_PUESTO VARCHAR2(50),
    DT_FECHA_INICIO DATE,
    DT_FECHA_ACTUALIZACION DATE
);


CREATE SEQUENCE SK_NUM_DIM_EMPLEADO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


--################################################################CODIGOS CREACION STG Y DIM PRODUCTO########
CREATE TABLE STG_PRODUCTO(
    CODIGO_PRODUCTO VARCHAR2(10),
    NOMBRE VARCHAR2(40),
    MARCA VARCHAR2(25),
    PROVEEDOR VARCHAR2(25),
    DESCRIPCION VARCHAR2(150),
    CANTIDAD NUMBER(3),
    PRECIO_VENTA NUMBER(6),
    PRECIO_PROVEEDOR NUMBER(6)
);


CREATE TABLE DIM_PRODUCTO(
    SK_NUM_DIM_PRODUCTO NUMBER(4),
    STR_CODIGO_PRODUCTO VARCHAR2(10),
    STR_NOMBRE VARCHAR2(40),
    STR_MARCA VARCHAR2(25),
    STR_PROVEEDOR VARCHAR2(25),
    STR_DESCRIPCION VARCHAR2(150),
    NUM_CANTIDAD NUMBER(3),
    NUM_PRECIO_VENTA NUMBER(6),
    NUM_PRECIO_PROVEEDOR NUMBER(6),
    DT_FECHA_INICIO DATE,
    DT_FECHA_ACTUALIZACION DATE
);


CREATE SEQUENCE SK_NUM_DIM_PRODUCTO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;



--#####################################################CODIGOS CREACION STG DIM CLIENTE################
CREATE TABLE STG_CLIENTE_D(
    CODIGO_CLIENTE VARCHAR2(10),
    cedula NUMBER(12),
    nombre VARCHAR2(30),
    apellido VARCHAR2(30),
    telefono VARCHAR2(15),
    direccion VARCHAR2(100),
    ciudad VARCHAR2(30)
);


CREATE TABLE DIM_CLIENTE_D(
    SK_NUM_DIM_CLIENTE_D NUMBER(3),
    STR_CODIGO_CLIENTE VARCHAR2(10),
    NUM_cedula NUMBER(12),
    STR_nombre VARCHAR2(30),
    STR_apellido VARCHAR2(30),
    STR_telefono VARCHAR2(15),
    STR_direccion VARCHAR2(100),
    STR_ciudad VARCHAR2(30),
    DT_FECHA_INICIO DATE,
    DT_FECHA_ACTUALIZACION DATE
);

CREATE SEQUENCE SK_NUM_DIM_CLIENTE_D
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


--##########################################################CODIGO DIM TIEMPO ##########################
CREATE TABLE DIM_TIEMPO(
    SK_NUM_DIM_TIEMPO NUMBER(7),
    NUM_ID_FECHA NUMBER(8),
    DT_FECHA DATE,
    NUM_AÑO NUMBER(4),
    NUM_MES NUMBER(2),
    STR_NOMBRE_MES VARCHAR2(15),
    NUM_TRIMESTRE NUMBER(1),
    NUM_SEMANA NUMBER(2),
    STR_NOMBRE_DIA VARCHAR2(15),
    NUM_DIA NUMBER(3),
    STR_FIN_SEMANA CHAR(2) CHECK(STR_FIN_SEMANA IN ('SI', 'NO')),
    STR_BISIESTO CHAR(2) CHECK(STR_BISIESTO IN ('SI', 'NO'))
);


CREATE SEQUENCE SK_NUM_DIM_TIEMPO_D
START WITH 1
INCREMENT BY 1
NOCACHE;


DECLARE
    V_FECHA DATE := TO_DATE('01-01-2020', 'DD-MM-YYYY');
BEGIN
    WHILE V_FECHA <= TO_DATE('31-12-2035', 'DD-MM-YYYY') LOOP
        INSERT INTO DIM_TIEMPO_D (
            SK_NUM_DIM_TIEMPO, NUM_ID_FECHA, DT_FECHA, NUM_AÑO, NUM_MES, STR_NOMBRE_MES, NUM_TRIMESTRE, NUM_SEMANA,
            STR_NOMBRE_DIA, NUM_DIA, STR_FIN_SEMANA, STR_BISIESTO
        ) VALUES (
            SEQ_SK_DIM_TIEMPO.NEXTVAL,
            TO_NUMBER(TO_CHAR(V_FECHA, 'YYYYMMDD')),  -- NUM_ID_FECHA 
            V_FECHA,
            EXTRACT(YEAR FROM V_FECHA),
            EXTRACT(MONTH FROM V_FECHA),
            TO_CHAR(V_FECHA, 'Month', 'NLS_DATE_LANGUAGE = SPANISH'),
            CEIL(EXTRACT(MONTH FROM V_FECHA) / 3),
            TO_CHAR(V_FECHA, 'IW'),  -- Número de semana del año
            TO_CHAR(V_FECHA, 'Day', 'NLS_DATE_LANGUAGE = SPANISH'),
            TO_CHAR(V_FECHA, 'DDD'),
            CASE WHEN TO_CHAR(V_FECHA, 'D') IN ('1', '7') THEN 'SI' ELSE 'NO' END,
            CASE WHEN MOD(EXTRACT(YEAR FROM V_FECHA), 4) = 0 AND 
                    (MOD(EXTRACT(YEAR FROM V_FECHA), 100) <> 0 OR 
                    MOD(EXTRACT(YEAR FROM V_FECHA), 400) = 0) THEN 'SI' ELSE 'NO' END
        );
        
        V_FECHA := V_FECHA + 1;  -- Avanzar un día
    END LOOP;
    COMMIT;
END;
/

--##########################################################CODIGOS STG Y DIM_ESTADO_PEDIDO##################

CREATE TABLE STG_ESTADO_PEDIDO(
    CODIGO_PEDIDO VARCHAR2(10),
    ESTADO VARCHAR2(15),
);


CREATE TABLE DIM_ESTADO_PEDIDO(
    SK_NUM_DIM_ESTADO_PEDIDO NUMBER(5),
    STR_CODIGO_PEDIDO VARCHAR2(10),
    STR_ESTADO VARCHAR2(15),
    DT_FECHA_INICIO DATE,
    DT_FECHA_ACTUALIZACION DATE
);

CREATE SEQUENCE SK_NUM_DIM_ESTADO_PEDIDO
START WITH 1
INCREMENT BY 1
NOCACHE;


